site_name: AjaxUpload
docs_dir: core/components/ajaxupload/docs/mkdocs
site_dir: _build/site

repo_url: https://github.com/Jako/AjaxUpload

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Contributors: 'contributors.md'
- Donate: 'donate.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables